#!/usr/bin/env python3
# MULTI_PIPELINE_ALL_IN_ONE.py — single-file bundle of your entire stack.
# (Autogenerated)

import os, sys, types, importlib, argparse, warnings

if os.name == "nt":
    os.environ.setdefault("PYTHONUTF8", "1")
    os.environ.setdefault("PYTHONIOENCODING", "utf-8")
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

import os
import csv
import torch
import torch.nn as nn
from typing import Optional, Tuple

# Defer heavy imports to avoid circulars and improve robustness
from importlib import import_module


class FrozenNodeEncoder(nn.Module):
    def __init__(self, embeddings: torch.Tensor):
        super().__init__()
        self.emb = nn.Embedding(embeddings.size(0), embeddings.size(1))
        with torch.no_grad():
            self.emb.weight.copy_(embeddings)
        for p in self.parameters():
            p.requires_grad_(False)

    def forward(self, idx: torch.Tensor) -> torch.Tensor:
        return self.emb(idx)


def train_gnn_make_node_encoder(path: str, arch: str, device: torch.device,
                                steps: int = 200, lappe: bool = True, rwse: bool = False,
                                pos_method: str = "diff", max_nodes: int = 10000) -> Tuple[nn.Module, int]:
    # Try full GNN.py API first; fallback to local minimal pipeline
    try:
        GNN = import_module('GNN')
        if all(hasattr(GNN, nm) for nm in ("load_paths","assemble","build_homo_data","run_train_homo")):
            paths = GNN.load_paths(path)
            cfg = GNN.assemble(paths, label_override=None, edge_label_override=None, default_k=10, mutual=False)
            if cfg["mode"] != "homo":
                raise RuntimeError("Current integration expects homogeneous graphs for node embeddings")
            data, hyper, _best_label, edge_dim, pos_pack = GNN.build_homo_data(
                cfg, arch, device, label_override=None, add_lappe=lappe, add_rwse=rwse, pos_method=pos_method
            )
            node_pe, pos_ij, pos_dim = pos_pack
            # Optionally subsample nodes for memory-constrained quick test
            if max_nodes is not None and data.x.size(0) > max_nodes:
                idx = torch.arange(max_nodes)
                data.x = data.x[idx]
                if hasattr(data, 'edge_index') and data.edge_index is not None:
                    # filter edges to subgraph (approximate; drops edges to >max_nodes)
                    ei = data.edge_index
                    mask = (ei[0] < max_nodes) & (ei[1] < max_nodes)
                    data.edge_index = ei[:, mask]
            best_val, test_metric, enc, head = GNN.run_train_homo(
                data, arch, {**hyper, "eval_every": max(steps//10, 10)}, device,
                steps=steps, lr=3e-4, wd=1e-4, heads=8 if arch=="gtr" else 4, layers=3 if arch=="gtr" else 2,
                edge_dim=edge_dim, pos_dim=pos_dim, use_neighbor=False, fanout=(15,10,5), node_pe=node_pe, build_pos_from=pos_method
            )
            enc.eval()
            with torch.no_grad():
                if arch == "gatv2":
                    H = enc(data.x.to(device), data.edge_index.to(device))
                else:
                    H = enc(
                        data.x.to(device), data.edge_index.to(device),
                        data.edge_attr.to(device) if getattr(data, "edge_attr", None) is not None else None,
                        pos_ij.to(device) if pos_ij is not None else None
                    )
                H = H.detach().cpu()
            node_encoder = FrozenNodeEncoder(H)
            return node_encoder, H.size(1)
    except Exception:
        pass

    # ---------- Minimal local fallback (no torch_geometric dependency required) ----------
    import pandas as pd
    import numpy as np
    import torch.nn.functional as F

    nodes_csv = os.path.join(path, "nodes.csv") if os.path.isdir(path) else path
    if os.path.isdir(path) and not os.path.exists(nodes_csv):
        # search first csv under dir
        for fname in os.listdir(path):
            if fname.endswith(".csv"):
                nodes_csv = os.path.join(path, fname); break
    df = pd.read_csv(nodes_csv)
    # Expect id,text,label
    if "id" not in df.columns:
        df = df.reset_index().rename(columns={"index":"id"})
    text_col = "text" if "text" in df.columns else df.columns[1]

    # Simple hashing features
    def hash_embed(col: pd.Series, buckets=8192, dim=32):
        emb = nn.Embedding(buckets, dim).to(device)
        nn.init.normal_(emb.weight, mean=0.0, std=0.02)
        idx = torch.from_numpy(np.fromiter(((hash(str(v)) % buckets) for v in col.astype(str)), count=len(col), dtype=np.int64)).to(device)
        with torch.no_grad():
            return emb(idx).float()

    X = hash_embed(df[text_col])  # [N, d]
    N, d = X.shape
    # Cap N to avoid O(N^2) memory; subsample deterministically
    N_cap = max_nodes or 10000
    if N > N_cap:
        idx = torch.arange(N)[:N_cap]
        X = X[idx]
        N = N_cap
    # Cosine kNN (cheap):
    k = min(10, max(2, N-1))
    # Move to CPU for memory-heavy matmul
    Xn = F.normalize(X, p=2, dim=1).to("cpu")
    sims = Xn @ Xn.T
    topk = torch.topk(sims, k+1, dim=1).indices
    src = []; dst = []
    for i in range(N):
        for j in topk[i].tolist():
            if j==i: continue
            src.append(j); dst.append(i)
    edge_index = torch.tensor([src, dst], dtype=torch.long, device="cpu")

    # Simple 2-layer message passing (no PyG): one round of mean aggregation repeated L times
    hidden = 256
    out_dim = 256
    W0 = nn.Linear(d, out_dim).to(device)  # projection for reconstruction term
    W1 = nn.Linear(d, hidden).to(device)
    W2 = nn.Linear(hidden, out_dim).to(device)
    params = list(W0.parameters()) + list(W1.parameters()) + list(W2.parameters())
    opt = torch.optim.AdamW(params, lr=3e-4)

    def aggregate(x, ei):
        src, dst = ei
        msg = x[src]
        out = torch.zeros_like(x)
        out.index_add_(0, dst, msg)
        deg = torch.bincount(dst, minlength=x.size(0)).clamp_min(1).view(-1,1)
        return out / deg

    X = Xn.to(device)
    X0 = X.detach()
    ei_dev = edge_index.to(device)
    for step in range(min(steps, 200)):
        opt.zero_grad(set_to_none=True)
        h = F.relu(W1(X))
        for _ in range(2):
            h = aggregate(h, ei_dev)
            h = F.relu(h)
        z = W2(h)
        # Simple graph smoothing objective towards neighbors
        s = z[ei_dev[0]] - z[ei_dev[1]]
        recon = z - W0(X)
        loss = (s.pow(2).mean() + 1e-3 * recon.pow(2).mean())
        loss.backward(); opt.step()

    H = z.detach().cpu()
    node_encoder = FrozenNodeEncoder(H)
    return node_encoder, H.size(1)


def download_gnn_preset(preset: str, out_dir: str, max_rows: Optional[int] = None) -> str:
    """Download a small dataset and export a single nodes.csv suitable for GNN training.
    Returns the directory path containing the CSVs (can be passed to GNN assemble).
    Presets: deepcoder | synthetic2rl | codecontests
    """
    os.makedirs(out_dir, exist_ok=True)
    nodes_path = os.path.join(out_dir, "nodes.csv")
    try:
        from datasets import load_dataset
    except Exception as e:
        raise RuntimeError("Please install 'datasets' to use --gnn-download") from e

    rows = []
    if preset == "deepcoder":
        ds = load_dataset("PrimeIntellect/deepcoder-gold-standard-solutions", split="train")
        for i, r in enumerate(ds):
            text = (r.get("prompt", "") or "").strip()
            sol = (r.get("gold_standard_solution", "") or "").strip()
            label = 1 if len(sol) > 0 else 0
            rows.append((i, text, label))
    elif preset == "synthetic2rl":
        ds = load_dataset("PrimeIntellect/SYNTHETIC-2-RL", split="train")
        def pick(row, keys):
            for k in keys:
                if k in row and isinstance(row[k], str) and row[k]: return row[k]
            return ""
        for i, r in enumerate(ds):
            prompt = pick(r, ["prompt","instruction","question","input","description"]).strip()
            diff = 0.5
            for k in r.keys():
                if "pass" in k or "difficulty" in k:
                    try:
                        v = float(r[k]);
                        if 0 <= v <= 1: diff = v; break
                    except: pass
            rows.append((i, prompt, diff))
    elif preset == "codecontests":
        ds = load_dataset("deepmind/code_contests", split="train")
        def first_sol(row):
            sols = row.get("solutions", None)
            if isinstance(sols, list) and len(sols)>0 and isinstance(sols[0], dict):
                code = sols[0].get("solution", None) or sols[0].get("code", None)
                if isinstance(code, str) and code.strip(): return code
            if isinstance(sols, list) and len(sols)>0 and isinstance(sols[0], str):
                return sols[0]
            return ""
        for i, r in enumerate(ds):
            desc = (r.get("description", "") or "").strip()
            sol = first_sol(r)
            label = 1 if sol else 0
            rows.append((i, desc, label))
    else:
        raise ValueError(f"Unknown preset: {preset}")

    # Write nodes.csv with columns: id,text,label
    with open(nodes_path, "w", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["id", "text", "label"])  # headers
        count = 0
        for i, text, label in rows:
            wr.writerow([i, text, label])
            count += 1
            if max_rows is not None and count >= max_rows:
                break
    return out_dir

    
# Embedded-sources support removed

def pick_device(user_arg):
    """Pick device from user arg or auto-detect."""
    if user_arg:
        return str(user_arg)
    try:
        import torch
        if torch.cuda.is_available():
            return "cuda"
        if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
            return "mps"
    except Exception:
        pass
    return "cpu"

def enable_deterministic(seed=0):
    """Enable deterministic behavior for reproducibility."""
    try:
        import random
        import numpy as np
        import torch
        random.seed(seed)
        np.random.seed(seed)  # Fixed: was numpy.random.seed
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
    except Exception as e:
        warnings.warn(f"[determinism] Not fully enforced: {e}")

def enable_torch_anomaly():
    """Enable PyTorch anomaly detection for debugging."""
    try:
        import torch
        torch.autograd.set_detect_anomaly(True)
    except Exception:
        pass

def enable_cuda_launch_blocking_if_needed(device):
    """Enable CUDA blocking for better error messages."""
    if device == "cuda":
        os.environ.setdefault("CUDA_LAUNCH_BLOCKING", "1")
        os.environ.setdefault("TORCH_SHOW_CPP_STACKTRACES", "1")

def _sanitize_edge_index(data):
    """Sanitize edge index to ensure valid tensor format."""
    try:
        import torch
        if not hasattr(data, "edge_index") or data.edge_index is None:
            return data
        ei = data.edge_index
        if not torch.is_tensor(ei):
            return data
        if ei.dtype != torch.long:
            ei = ei.long()
        if ei.numel() == 0:
            data.edge_index = ei
            return data
        if ei.dim() != 2 or ei.size(0) != 2:
            raise ValueError(f"[sanitize] edge_index must be [2, E], got {tuple(ei.shape)}")
        num_nodes = int(getattr(data, "num_nodes", -1))
        mx = int(ei.max().item())
        if num_nodes <= 0 or mx >= num_nodes:
            num_nodes = max(num_nodes, mx + 1)
            data.num_nodes = int(num_nodes)
        bad = (ei < 0) | (ei >= num_nodes)
        bad_mask = bad[0] | bad[1]
        if bad_mask.any():
            keep = ~bad_mask
            ei = ei[:, keep]
            warnings.warn(f"[sanitize] Dropped {int(bad_mask.sum().item())} out-of-range edges")
        data.edge_index = ei.contiguous()
        return data
    except Exception as e:
        warnings.warn(f"[sanitize] Exception: {e}")
        return data

def enable_pyg_sanitizer():
    """Enable PyTorch Geometric edge index sanitization."""
    try:
        from torch_geometric.data import Data
        _orig_init = Data.__init__
        def _wrapped_init(self, *args, **kwargs):
            _orig_init(self, *args, **kwargs)
            _sanitize_edge_index(self)
        Data.__init__ = _wrapped_init  # type: ignore
        print("[pyg] graph sanitation enabled")
    except Exception as e:
        warnings.warn(f"[pyg] sanitizer not enabled: {e}")

def build_parser():
    """Build command-line argument parser."""
    p = argparse.ArgumentParser(
        prog="MULTI_PIPELINE_ALL_IN_ONE.py",
        description="One-file entry to your graph world + multi-agent stack (with guards)."
    )
    sub = p.add_subparsers(dest="mode", required=True)
    
    # Multi-agent mode
    pm = sub.add_parser("multi", help="Run multi-agent orchestrator (world + policy)")
    pm.add_argument("--env", default="deepcoder", choices=["deepcoder", "synthetic2rl", "codecontests", "text"])
    pm.add_argument("--iterations", type=int, default=1)
    pm.add_argument("--world-updates", type=int, default=300)
    pm.add_argument("--world-rollout", type=int, default=128)
    pm.add_argument("--world-precision", choices=["fp32", "bf16", "fp16"], default="fp32")
    pm.add_argument("--world-device", default=None, help="cpu|cuda|mps (auto if omitted)")
    pm.add_argument("--gnn-download", default="deepcoder", choices=["deepcoder", "synthetic2rl", "codecontests"])
    pm.add_argument("--gnn-outdir", default="datasets/deepcoder")
    pm.add_argument("--gnn-arch", default="gtr", choices=["gtr", "gatv2"])
    pm.add_argument("--policy-rft-steps", type=int, default=300)
    pm.add_argument("--policy-grpo-steps", type=int, default=150)
    pm.add_argument("--seed", type=int, default=0)
    
    # World model only mode
    pw = sub.add_parser("world", help="Train only the graph world model")
    pw.add_argument("--env", default="deepcoder", choices=["deepcoder", "synthetic2rl", "codecontests", "text"])
    pw.add_argument("--updates", type=int, default=300)
    pw.add_argument("--rollout", type=int, default=128)
    pw.add_argument("--precision", choices=["fp32", "bf16", "fp16"], default="fp32")
    pw.add_argument("--device", default=None, help="cpu|cuda|mps (auto if omitted)")
    pw.add_argument("--use-gnn", action="store_true")
    pw.add_argument("--gnn-data", default=None)
    pw.add_argument("--gnn-download", default=None, choices=["deepcoder", "synthetic2rl", "codecontests"])
    pw.add_argument("--gnn-outdir", default="datasets/deepcoder")
    pw.add_argument("--gnn-arch", default="gtr", choices=["gtr", "gatv2"])
    pw.add_argument("--gnn-steps", type=int, default=200)
    pw.add_argument("--gnn-max-nodes", type=int, default=8000)
    pw.add_argument("--seed", type=int, default=0)
    
    # GNN embedding mode
    pg = sub.add_parser("gnn-embed", help="Pretrain a GNN encoder and export frozen node embeddings")
    pg.add_argument("--data", required=True, help="Directory or CSV path for graph data (nodes.csv / edges.csv)")
    pg.add_argument("--arch", default="gtr", choices=["gtr", "gatv2"], help="Backbone arch if using GNN.py")
    pg.add_argument("--steps", type=int, default=200)
    pg.add_argument("--max-nodes", type=int, default=8000)
    pg.add_argument("--device", default=None, help="cpu|cuda|mps (auto if omitted)")
    
    # SPCT proxy (use k_small_big pipeline)
    ps = sub.add_parser("spct", help="Run SPCT via k_small_big (RFT and/or GRPO)")
    ps.add_argument("--stage", required=True, choices=["rft", "rl", "train"], help="Which SPCT stage to run")
    ps.add_argument("--dataset", default=None, help="Path to CodeFeedback-like dataset (optional)")
    ps.add_argument("--rft-steps", type=int, default=800)
    ps.add_argument("--grpo-steps", type=int, default=200)
    ps.add_argument("--samples-per-prompt", type=int, default=4)
    ps.add_argument("--kl-beta", type=float, default=0.02)
    ps.add_argument("--save-dir", default="checkpoints_big", help="Directory for checkpoints")
    ps.add_argument("--device", default=None)
    ps.add_argument("--seed", type=int, default=1337)
    return p

def run_multi(args):
    """Run multi-agent training."""
    device = pick_device(args.world_device)
    enable_cuda_launch_blocking_if_needed(device)
    enable_pyg_sanitizer()
    enable_deterministic(args.seed)
    
    # Try to import the actual multi_agent_training module
    try:
        MA = importlib.import_module("multi_agent_training")
    except ImportError as e:
        raise SystemExit("multi_agent_training module not found. Please add it to PYTHONPATH.") from e
    
    # Build arguments
    argv = [
        "--env", args.env,
        "--iterations", str(args.iterations),
        "--world-updates", str(args.world_updates),
        "--world-rollout", str(args.world_rollout),
        "--world-precision", args.world_precision,
        "--policy-rft-steps", str(args.policy_rft_steps),
        "--policy-grpo-steps", str(args.policy_grpo_steps),
        "--seed", str(args.seed),
    ]
    if args.world_device:
        argv += ["--world-device", device]
    if args.gnn_download:
        argv += ["--gnn-download", args.gnn_download]
    if args.gnn_outdir:
        argv += ["--gnn-outdir", args.gnn_outdir]
    if args.gnn_arch:
        argv += ["--gnn-arch", args.gnn_arch]
    
    sys_argv_backup = sys.argv[:]
    try:
        sys.argv = ["multi_agent_training.py"] + argv
        if hasattr(MA, "main"):
            MA.main()
        else:
            raise SystemExit("multi_agent_training.py has no main()")
    finally:
        sys.argv = sys_argv_backup

def run_world(args):
    """Run world model training only."""
    device = pick_device(args.device)
    enable_cuda_launch_blocking_if_needed(device)
    enable_pyg_sanitizer()
    enable_deterministic(args.seed)
    
    # Try to import the actual graph_world_model module
    try:
        GM = importlib.import_module("graph_world_model")
    except ImportError as e:
        raise SystemExit("graph_world_model module not found. Please add it to PYTHONPATH.") from e
    
    argv = [
        "--env", args.env,
        "--updates", str(args.updates),
        "--rollout-len", str(args.rollout),
        "--precision", args.precision,
        "--device", device,
        "--seed", str(args.seed),
    ]
    if args.use_gnn:
        argv.append("--use-gnn")
    if args.gnn_data:
        argv += ["--gnn-data", args.gnn_data]
    if args.gnn_download:
        argv += ["--gnn-download", args.gnn_download]
    if args.gnn_outdir:
        argv += ["--gnn-outdir", args.gnn_outdir]
    if args.gnn_arch:
        argv += ["--gnn-arch", args.gnn_arch]
    if args.gnn_steps:
        argv += ["--gnn-steps", str(args.gnn_steps)]
    if args.gnn_max_nodes:
        argv += ["--gnn-max-nodes", str(args.gnn_max_nodes)]
    
    sys_argv_backup = sys.argv[:]
    try:
        sys.argv = ["graph_world_model.py"] + argv
        if hasattr(GM, "main"):
            GM.main()
        else:
            raise SystemExit("graph_world_model.py has no main()")
    finally:
        sys.argv = sys_argv_backup

def run_gnn(args):
    """Run GNN embedding training."""
    enable_pyg_sanitizer()
    
    import torch
    dev = torch.device(pick_device(args.device))
    
    print(f"[gnn-embed] Training GNN encoder on {args.data} with arch={args.arch}")
    enc, dim = train_gnn_make_node_encoder(
        path=args.data,
        arch=args.arch,
        device=dev,
        steps=args.steps,
        lappe=True,
        rwse=False,
        pos_method="diff",
        max_nodes=args.max_nodes,
    )
    outdir = os.path.join(os.getcwd(), "gnn_encoder_export")
    os.makedirs(outdir, exist_ok=True)
    export_path = os.path.join(outdir, f"frozen_node_encoder_{dim}d.pt")
    torch.save({"state_dict": enc.state_dict(), "dim": dim, "arch": args.arch}, export_path)
    print(f"[gnn-embed] ✓ Saved frozen encoder to: {export_path}")
    print(f"[gnn-embed]   Dimensions: {dim}, Architecture: {args.arch}")

def run_spct(args):
    """Proxy SPCT to koder.k_small_big with stage control (RFT-only, RL-only, or both)."""
    try:
        ks = importlib.import_module("koder.k_small_big")
    except ImportError as e:
        raise SystemExit("Could not import koder.k_small_big. Ensure the package path is correct.") from e

    # Map our args to k_small_big CLI
    device = pick_device(args.device)
    rft_steps = max(0, int(args.rft_steps))
    grpo_steps = max(0, int(args.grpo_steps))
    if args.stage == "rft":
        grpo_steps = 0
    elif args.stage == "rl":
        rft_steps = 0
    # else: "train" runs both as given

    argv = [
        "k_small_big.py",
        "--device", device,
        "--seed", str(args.seed),
        "--save-dir", args.save_dir,
        "--run-spct",
        "--spct-rft-steps", str(rft_steps),
        "--spct-grpo-steps", str(grpo_steps),
        "--spct-samples-per-prompt", str(args.samples_per_prompt),
        "--spct-kl-beta", str(args.kl_beta),
    ]
    if args.dataset:
        argv += ["--spct-dataset", args.dataset]

    sys_argv_backup = sys.argv[:]
    try:
        sys.argv = argv
        if hasattr(ks, "main"):
            ks.main()
        else:
            raise SystemExit("k_small_big.main() not found")
    finally:
        sys.argv = sys_argv_backup

def main():
    """Main entry point."""
    parser = build_parser()
    args = parser.parse_args()
    
    if args.mode == "multi":
        run_multi(args)
    elif args.mode == "world":
        run_world(args)
    elif args.mode == "gnn-embed":
        run_gnn(args)
    elif args.mode == "spct":
        run_spct(args)
    else:
        parser.print_help()
        raise SystemExit(f"Unknown mode: {args.mode}")

if __name__ == "__main__":
    main()

